{{- if and .Values.global.postgresql.postgresqlExternalHost (not .Values.global.postgresql.existingSecret ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
{{- include "prefect-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.global.postgresql.postgresqlPostgresPassword }}
  postgresql-postgres-password: {{ .Values.global.postgresql.postgresqlPostgresPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresqlPassword }}
  postgresql-password: {{ .Values.postgresqlPassword | b64enc | quote }}
  {{- end }}
{{- end -}}