{{- if .Values.apollo.ingress.enabled -}}
{{- $svcPort := .Values.global.apollo.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "apollo.fullname" . }}
  labels:
    {{- include "apollo.labels" . | nindent 4 }}
  {{- with .Values.apollo.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.apollo.ingress.tls }}
  tls:
  {{- range .Values.apollo.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  {{- if .Values.apollo.ingress.hosts  -}}
  rules:
    {{- range .Values.apollo.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ include "apollo.fullname" . }}
              servicePort: {{ $svcPort }}
        {{- end }}
    {{- end }}
  {{- end -}}
{{- end -}}
