apiVersion: v1
kind: Service
metadata:
  name: {{ include "apollo.fullname" . }}
  labels: 
    {{- include "apollo.labels" . | nindent 4 }}
  {{- if ( include "apollo.annotations" . ) }}
  annotations:
    {{- ( include "apollo.annotations" . ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apollo.service.type }}
  ports:
    - port: {{ .Values.global.apollo.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "apollo.selectorLabels" . | nindent 4 }}
